package com.nordstrom.emulator;

import java.awt.event.KeyEvent;

/**
 * Translates real Swing/AWT key events into the Apple II+'s own ASCII
 * keyboard convention. Lives alongside {@link Apple2Plus}, not in the
 * toolkit-agnostic {@code system} package, since translating from a
 * specific UI toolkit's own event representation is this class's
 * entire reason to exist -- unlike
 * {@link com.nordstrom.emulator.system.KeyboardRegister}, which
 * deliberately has no opinion about where a keypress comes from.
 * <p>
 * Real, stock Apple II+ hardware fact this reflects: the keyboard has
 * NO lowercase capability at all -- letters always send their uppercase
 * ASCII code, regardless of shift state or what Java's own key handling
 * produced. Ctrl+letter sends the standard ASCII control code
 * ({@code letter & 0x1F}, computed here as an offset from {@code VK_A}),
 * a general rule rather than per-key special-casing. Left-arrow doubles
 * as the era's backspace-equivalent ($08).
 * <p>
 * Split into two methods rather than one taking a full {@link KeyEvent},
 * matching how Swing itself delivers keyboard input in two distinct
 * event types: {@code KEY_TYPED} carries a real, already-shift-resolved
 * character (letters, digits, punctuation), while {@code KEY_PRESSED}
 * is what carries non-printable keys (ENTER, ESC, arrows) and modifier
 * state (Ctrl) that {@code KEY_TYPED} doesn't reliably expose. This
 * split also keeps both methods testable with plain primitives, not
 * full {@code KeyEvent} objects, which have to be actually generated by
 * a real windowing system to be trustworthy -- something this project's
 * headless sandbox can't do.
 * <p>
 * Deliberately incomplete: this covers what's needed to type at a
 * BASIC/Monitor prompt (letters, digits, common punctuation, RETURN,
 * left-arrow, ESC, and Ctrl-combinations) -- not full fidelity to every
 * key the real keyboard and its era-specific quirks had.
 */
public final class KeyboardMapper {

    /**
     * Maps a typed character (from a Swing {@code KEY_TYPED} event) to
     * the Apple II+'s own ASCII convention.
     *
     * @param typed the character Java reports as typed
     * @return the Apple II+ ASCII value, or -1 if not printable
     */
    public static int mapTypedCharacter(char typed) {
        if (typed >= 0x20 && typed < 0x7F) {
            return Character.toUpperCase(typed);
        }
        return -1;
    }

    /**
     * Maps a non-printable key press (from a Swing {@code KEY_PRESSED}
     * event) to the Apple II+'s own ASCII convention.
     *
     * @param keyCode the AWT {@code VK_*} key code
     * @param ctrlDown whether Ctrl was held
     * @return the Apple II+ ASCII value, or -1 if unmapped
     */
    public static int mapSpecialKey(int keyCode, boolean ctrlDown) {
        if (ctrlDown && keyCode >= KeyEvent.VK_A && keyCode <= KeyEvent.VK_Z) {
            return keyCode - KeyEvent.VK_A + 1; // Ctrl-A=$01 .. Ctrl-Z=$1A
        }
        return switch (keyCode) {
            case KeyEvent.VK_ENTER -> 0x0D;
            case KeyEvent.VK_LEFT, KeyEvent.VK_BACK_SPACE -> 0x08;
            case KeyEvent.VK_ESCAPE -> 0x1B;
            default -> -1;
        };
    }

    private KeyboardMapper() {}
}
